Homework 2
Vtal9/smart-home-2020 pull request #2
Opened 2020-03-14 13:01 UTC by Vtal9

2020-03-16 07:24 UTC, a-ivanov requested changes

2020-03-16 07:24 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/DoorEventProcessor.java
> +                            System.out.println("Door " + door.getId() + " was opened.");
Логировать можно одной строчкой, DRY принцип.

2020-03-16 07:24 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/EventCreator.java
> +    public static SensorEvent getNextSensorEvent() {
Лучше сделать интерфейс +имплементацию классом без статических методов http://bit.ly/3aLBprl

2020-03-16 07:24 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/HallDoorEvenProcessor.java
> +            Room room = (Room) homeComponent;
Здесь будет https://docs.oracle.com/javase/7/docs/api/index.html?java/lang/ClassCastException.html не для комнаты. Добавьте проверку instanceof https://www.baeldung.com/java-instanceof. А вообще эта ошибка должна была всплыть у вас при написании юнит теста.

2020-03-16 07:24 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/SmartHome.java
>      public Collection<Room> getRooms() {
Этот метод по заданию 2 необходимо удалить http://bit.ly/2U6PHMN

2020-03-17 23:44 UTC, Vtal9 commented on src/main/java/ru/sbt/mipt/oop/HallDoorEvenProcessor.java
> +            Room room = (Room) homeComponent;
там чуть выше есть проверка

2020-03-18 06:34 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/HallDoorEvenProcessor.java
> +            Room room = (Room) homeComponent;
Вижу, ок.

2020-03-18 06:35 UTC, a-ivanov approved these changes

2020-03-18 19:56 UTC, merged